[package]
name = "if_let_with_else"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
whisker-rust = { path = "../../crates/whisker-rust" }
whisker-types = { path = "../../crates/whisker-types" }

[dev-dependencies]
whisker-testing = { path = "../../crates/whisker-testing" }

[lints]
workspace = true
